// The service worker: what makes Little RPG installable and playable
// with the plane in the air.
//
// GENERATED by tools/build_sw.py -- do not edit by hand, the precache list
// and the version stamp are walked from the repo and rebuilt every time.
//
// Cache-first for the shell, because every byte of this game is static and
// versioned: if it is in the cache it is the right file, and the stamp
// changes the moment any of them does. Network-only for the leaderboard,
// so an offline player keeps playing and simply does not submit.
const VERSION = 'a4f2425eaa47';
const CACHE = `little-rpg-${VERSION}`;
const SHELL = [
  ".",
  "index.html",
  "styles.css",
  "manifest.json",
  "privacy.html",
  "src/format.js",
  "src/i18n.js",
  "src/main.js",
  "src/data/ancestors.js",
  "src/data/balance.js",
  "src/data/bestiary.js",
  "src/data/cosmos.js",
  "src/data/dishes.js",
  "src/data/dungeon.js",
  "src/data/enemies.js",
  "src/data/expeditions.js",
  "src/data/feats.js",
  "src/data/gathering.js",
  "src/data/gear.js",
  "src/data/gems.js",
  "src/data/jewels.js",
  "src/data/levels.js",
  "src/data/omni.js",
  "src/data/paths.js",
  "src/data/pets.js",
  "src/data/potions.js",
  "src/data/prestige.js",
  "src/data/quests.js",
  "src/data/skilltree.js",
  "src/data/sprites.js",
  "src/data/talents.js",
  "src/data/upgrades.js",
  "src/data/web.js",
  "src/engine/anim.js",
  "src/engine/loader.js",
  "src/engine/music.js",
  "src/engine/sfx.js",
  "src/game/battle.js",
  "src/game/render.js",
  "src/game/state.js",
  "src/net/config.js",
  "src/net/leaderboard.js",
  "src/store/billing.js",
  "src/ui/ui.js",
  "assets/manifest.json",
  "assets/app/apple-touch-icon.png",
  "assets/app/icon-192.png",
  "assets/app/icon-512.png",
  "assets/app/maskable-192.png",
  "assets/app/maskable-512.png",
  "assets/bg/far.png",
  "assets/bg/ground.png",
  "assets/bg/mid.png",
  "assets/bg/moon.png",
  "assets/bg/node_tree.png",
  "assets/bg/trees.png",
  "assets/characters/armored_orc/attack.png",
  "assets/characters/armored_orc/death.png",
  "assets/characters/armored_orc/hurt.png",
  "assets/characters/armored_orc/idle.png",
  "assets/characters/armored_orc/walk.png",
  "assets/characters/armored_skeleton/attack.png",
  "assets/characters/armored_skeleton/death.png",
  "assets/characters/armored_skeleton/hurt.png",
  "assets/characters/armored_skeleton/idle.png",
  "assets/characters/armored_skeleton/walk.png",
  "assets/characters/bat/attack.png",
  "assets/characters/bat/death.png",
  "assets/characters/bat/hurt.png",
  "assets/characters/bat/idle.png",
  "assets/characters/bat/walk.png",
  "assets/characters/black_knight_a/attack.png",
  "assets/characters/black_knight_a/death.png",
  "assets/characters/black_knight_a/hurt.png",
  "assets/characters/black_knight_a/idle.png",
  "assets/characters/black_knight_a/walk.png",
  "assets/characters/black_knight_b/attack.png",
  "assets/characters/black_knight_b/death.png",
  "assets/characters/black_knight_b/hurt.png",
  "assets/characters/black_knight_b/idle.png",
  "assets/characters/black_knight_b/walk.png",
  "assets/characters/black_knight_c/attack.png",
  "assets/characters/black_knight_c/death.png",
  "assets/characters/black_knight_c/hurt.png",
  "assets/characters/black_knight_c/idle.png",
  "assets/characters/black_knight_c/walk.png",
  "assets/characters/blood_monster_a/attack.png",
  "assets/characters/blood_monster_a/death.png",
  "assets/characters/blood_monster_a/hurt.png",
  "assets/characters/blood_monster_a/idle.png",
  "assets/characters/blood_monster_a/walk.png",
  "assets/characters/blood_monster_b/attack.png",
  "assets/characters/blood_monster_b/death.png",
  "assets/characters/blood_monster_b/hurt.png",
  "assets/characters/blood_monster_b/idle.png",
  "assets/characters/blood_monster_b/walk.png",
  "assets/characters/demon_a/attack.png",
  "assets/characters/demon_a/death.png",
  "assets/characters/demon_a/hurt.png",
  "assets/characters/demon_a/idle.png",
  "assets/characters/demon_a/walk.png",
  "assets/characters/demon_b/attack.png",
  "assets/characters/demon_b/death.png",
  "assets/characters/demon_b/hurt.png",
  "assets/characters/demon_b/idle.png",
  "assets/characters/demon_b/walk.png",
  "assets/characters/demon_c/attack.png",
  "assets/characters/demon_c/death.png",
  "assets/characters/demon_c/hurt.png",
  "assets/characters/demon_c/idle.png",
  "assets/characters/demon_c/walk.png",
  "assets/characters/demon_d/attack.png",
  "assets/characters/demon_d/death.png",
  "assets/characters/demon_d/hurt.png",
  "assets/characters/demon_d/idle.png",
  "assets/characters/demon_d/walk.png",
  "assets/characters/demon_e/attack.png",
  "assets/characters/demon_e/death.png",
  "assets/characters/demon_e/hurt.png",
  "assets/characters/demon_e/idle.png",
  "assets/characters/demon_e/walk.png",
  "assets/characters/demoness_a/attack.png",
  "assets/characters/demoness_a/death.png",
  "assets/characters/demoness_a/hurt.png",
  "assets/characters/demoness_a/idle.png",
  "assets/characters/demoness_a/walk.png",
  "assets/characters/demoness_b/attack.png",
  "assets/characters/demoness_b/death.png",
  "assets/characters/demoness_b/hurt.png",
  "assets/characters/demoness_b/idle.png",
  "assets/characters/demoness_b/walk.png",
  "assets/characters/elite_orc/attack.png",
  "assets/characters/elite_orc/death.png",
  "assets/characters/elite_orc/hurt.png",
  "assets/characters/elite_orc/idle.png",
  "assets/characters/elite_orc/walk.png",
  "assets/characters/eyeball_monster/attack.png",
  "assets/characters/eyeball_monster/death.png",
  "assets/characters/eyeball_monster/hurt.png",
  "assets/characters/eyeball_monster/idle.png",
  "assets/characters/eyeball_monster/walk.png",
  "assets/characters/flame_golem/attack.png",
  "assets/characters/flame_golem/death.png",
  "assets/characters/flame_golem/hurt.png",
  "assets/characters/flame_golem/idle.png",
  "assets/characters/flame_golem/walk.png",
  "assets/characters/ghostfire/attack.png",
  "assets/characters/ghostfire/death.png",
  "assets/characters/ghostfire/hurt.png",
  "assets/characters/ghostfire/idle.png",
  "assets/characters/ghostfire/walk.png",
  "assets/characters/greatsword_skeleton/attack.png",
  "assets/characters/greatsword_skeleton/death.png",
  "assets/characters/greatsword_skeleton/hurt.png",
  "assets/characters/greatsword_skeleton/idle.png",
  "assets/characters/greatsword_skeleton/walk.png",
  "assets/characters/hellbat/attack.png",
  "assets/characters/hellbat/death.png",
  "assets/characters/hellbat/hurt.png",
  "assets/characters/hellbat/idle.png",
  "assets/characters/hellbat/walk.png",
  "assets/characters/hellhound/attack.png",
  "assets/characters/hellhound/death.png",
  "assets/characters/hellhound/hurt.png",
  "assets/characters/hellhound/idle.png",
  "assets/characters/hellhound/walk.png",
  "assets/characters/knight/attack.png",
  "assets/characters/knight/death.png",
  "assets/characters/knight/hurt.png",
  "assets/characters/knight/idle.png",
  "assets/characters/knight/walk.png",
  "assets/characters/knight_templar/attack.png",
  "assets/characters/knight_templar/death.png",
  "assets/characters/knight_templar/hurt.png",
  "assets/characters/knight_templar/idle.png",
  "assets/characters/knight_templar/walk.png",
  "assets/characters/lava_slime/attack.png",
  "assets/characters/lava_slime/death.png",
  "assets/characters/lava_slime/hurt.png",
  "assets/characters/lava_slime/idle.png",
  "assets/characters/lava_slime/walk.png",
  "assets/characters/minotaur/attack.png",
  "assets/characters/minotaur/death.png",
  "assets/characters/minotaur/hurt.png",
  "assets/characters/minotaur/idle.png",
  "assets/characters/minotaur/walk.png",
  "assets/characters/necromancer/attack.png",
  "assets/characters/necromancer/death.png",
  "assets/characters/necromancer/hurt.png",
  "assets/characters/necromancer/idle.png",
  "assets/characters/necromancer/walk.png",
  "assets/characters/orc/attack.png",
  "assets/characters/orc/death.png",
  "assets/characters/orc/hurt.png",
  "assets/characters/orc/idle.png",
  "assets/characters/orc/walk.png",
  "assets/characters/orc_rider/attack.png",
  "assets/characters/orc_rider/death.png",
  "assets/characters/orc_rider/hurt.png",
  "assets/characters/orc_rider/idle.png",
  "assets/characters/orc_rider/walk.png",
  "assets/characters/skeleton/attack.png",
  "assets/characters/skeleton/death.png",
  "assets/characters/skeleton/hurt.png",
  "assets/characters/skeleton/idle.png",
  "assets/characters/skeleton/walk.png",
  "assets/characters/slime/attack.png",
  "assets/characters/slime/death.png",
  "assets/characters/slime/hurt.png",
  "assets/characters/slime/idle.png",
  "assets/characters/slime/walk.png",
  "assets/characters/swordsman/attack.png",
  "assets/characters/swordsman/death.png",
  "assets/characters/swordsman/hurt.png",
  "assets/characters/swordsman/idle.png",
  "assets/characters/swordsman/walk.png",
  "assets/characters/warlock/attack.png",
  "assets/characters/warlock/death.png",
  "assets/characters/warlock/hurt.png",
  "assets/characters/warlock/idle.png",
  "assets/characters/warlock/walk.png",
  "assets/characters/werebear/attack.png",
  "assets/characters/werebear/death.png",
  "assets/characters/werebear/hurt.png",
  "assets/characters/werebear/idle.png",
  "assets/characters/werebear/walk.png",
  "assets/characters/werewolf/attack.png",
  "assets/characters/werewolf/death.png",
  "assets/characters/werewolf/hurt.png",
  "assets/characters/werewolf/idle.png",
  "assets/characters/werewolf/walk.png",
  "assets/characters/wizard/attack.png",
  "assets/characters/wizard/death.png",
  "assets/characters/wizard/hurt.png",
  "assets/characters/wizard/idle.png",
  "assets/characters/wizard/walk.png",
  "assets/icons/icons.png",
  "assets/ui/bar_gold.png",
  "assets/ui/bar_red.png",
  "assets/ui/bar_track.png",
  "assets/ui/bar_violet.png",
  "assets/ui/board.png",
  "assets/ui/button.png",
  "assets/ui/button_disabled.png",
  "assets/ui/button_pressed.png",
  "assets/ui/check_off.png",
  "assets/ui/check_on.png",
  "assets/ui/frame_gem.png",
  "assets/ui/frame_lit.png",
  "assets/ui/plank.png",
  "assets/ui/plank_tall.png",
  "assets/ui/scroll.png",
  "assets/ui/wood.png"
];

self.addEventListener('install', (event) => {
  // Take over as soon as the new shell is down: an idle game that asks the
  // player to close every tab before it updates is an idle game nobody
  // updates.
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(SHELL))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((k) => k.startsWith('little-rpg-') && k !== CACHE)
          .map((k) => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);

  // Anything that is not ours -- the leaderboard, above all -- goes
  // straight to the network and is never stored.
  if (url.origin !== self.location.origin) return;

  // A navigation offline still opens the game: the shell answers for it.
  // The page asked for comes first, so an offline tap on the privacy policy
  // gets the privacy policy and not the game wearing its URL.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .catch(() => caches.match(request, { cacheName: CACHE, ignoreSearch: true })
          .then((hit) => hit || caches.match('index.html', { cacheName: CACHE })))
    );
    return;
  }

  event.respondWith(
    caches.match(request, { cacheName: CACHE, ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      // Something we did not precache (a build artifact, a stray asset):
      // fetch it and keep it, so the second time is offline-safe too.
      return fetch(request).then((res) => {
        if (!res || res.status !== 200 || res.type !== 'basic') return res;
        const copy = res.clone();
        caches.open(CACHE).then((cache) => cache.put(request, copy));
        return res;
      });
    })
  );
});
