#!/usr/bin/env python3
"""Write the service worker, with the whole game listed in its precache.

    python3 tools/build_sw.py

The list is WALKED, never hand-kept: 39 modules and 203 images is exactly
the kind of inventory a human forgets to update, and a service worker that
precaches a stale list is worse than none, because it serves the old file
forever. The version stamp is a hash of that list plus the bytes behind it,
so a changed pixel mints a new cache and the old one is dropped on
activate.

Nothing here touches the leaderboard: `src/net/` calls run network-only, so
an offline player keeps their save and simply does not submit.
"""
import hashlib
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "sw.js")

# Everything the game asks the network for on a cold boot.
ROOTS = ["src", "assets"]
FILES = [
    "index.html",
    "mobile.html",
    "styles.css",
    "mobile.css",
    "manifest.json",
    "manifest-mobile.json",
    "privacy.html",
]
SKIP_DIRS = {"__pycache__"}
KEEP = {".js", ".css", ".html", ".json", ".png", ".webp", ".ogg", ".mp3"}


def walk():
    out = list(FILES)
    for top in ROOTS:
        for dirpath, dirnames, filenames in os.walk(os.path.join(ROOT, top)):
            dirnames[:] = [d for d in sorted(dirnames) if d not in SKIP_DIRS]
            for name in sorted(filenames):
                if os.path.splitext(name)[1].lower() not in KEEP:
                    continue
                rel = os.path.relpath(os.path.join(dirpath, name), ROOT)
                out.append(rel.replace(os.sep, "/"))
    return out


def stamp(paths):
    h = hashlib.sha256()
    for rel in paths:
        h.update(rel.encode())
        with open(os.path.join(ROOT, rel), "rb") as fh:
            h.update(hashlib.sha256(fh.read()).digest())
    return h.hexdigest()[:12]


TEMPLATE = """// The service worker: what makes Little RPG installable and playable
// with the plane in the air.
//
// GENERATED by tools/build_sw.py -- do not edit by hand, the precache list
// and the version stamp are walked from the repo and rebuilt every time.
//
// Cache-first for the shell, because every byte of this game is static and
// versioned: if it is in the cache it is the right file, and the stamp
// changes the moment any of them does. Network-only for the leaderboard,
// so an offline player keeps playing and simply does not submit.
const VERSION = '{version}';
const CACHE = `little-rpg-${{VERSION}}`;
const SHELL = {shell};

self.addEventListener('install', (event) => {{
  // Take over as soon as the new shell is down: an idle game that asks the
  // player to close every tab before it updates is an idle game nobody
  // updates.
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(SHELL))
      .then(() => self.skipWaiting())
  );
}});

self.addEventListener('activate', (event) => {{
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((k) => k.startsWith('little-rpg-') && k !== CACHE)
          .map((k) => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
}});

self.addEventListener('fetch', (event) => {{
  const {{ request }} = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);

  // Anything that is not ours -- the leaderboard, above all -- goes
  // straight to the network and is never stored.
  if (url.origin !== self.location.origin) return;

  // A navigation offline still opens the game: the shell answers for it.
  // The page asked for comes first, so an offline tap on the privacy policy
  // gets the privacy policy and not the game wearing its URL.
  if (request.mode === 'navigate') {{
    event.respondWith(
      fetch(request)
        .catch(() => caches.match(request, {{ cacheName: CACHE, ignoreSearch: true }})
          .then((hit) => hit || caches.match('index.html', {{ cacheName: CACHE }})))
    );
    return;
  }}

  event.respondWith(
    caches.match(request, {{ cacheName: CACHE, ignoreSearch: true }}).then((hit) => {{
      if (hit) return hit;
      // Something we did not precache (a build artifact, a stray asset):
      // fetch it and keep it, so the second time is offline-safe too.
      return fetch(request).then((res) => {{
        if (!res || res.status !== 200 || res.type !== 'basic') return res;
        const copy = res.clone();
        caches.open(CACHE).then((cache) => cache.put(request, copy));
        return res;
      }});
    }})
  );
}});
"""


def main():
    paths = walk()
    # The single-file builds are downloads, not part of the app shell.
    paths = [p for p in paths if not p.startswith("little-rpg")]
    version = stamp(paths)
    shell = json.dumps(["."] + paths, indent=2)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(TEMPLATE.format(version=version, shell=shell))
    total = sum(os.path.getsize(os.path.join(ROOT, p)) for p in paths)
    print(f"sw.js  ({len(paths)} files, {total / 1024:.0f} KB, version {version})")


if __name__ == "__main__":
    main()
