#!/usr/bin/env python3
"""Render PRIVACY.md into the page a store asks you for.

    python3 tools/build_privacy.py

Google Play wants a privacy policy at a public URL, not a file in a repo,
and the two must not disagree. So the page is GENERATED from the markdown
and never hand-edited: PRIVACY.md stays the single source, and the hosted
page cannot drift behind it. `build_single_file.py` calls this before it
calls `build_sw.py`, so the worker precaches the fresh page.

The markdown here is a small, known dialect (headings, paragraphs, bullet
lists, one table, bold/italic/code spans), which is why this parses it in
sixty lines instead of pulling a dependency into a project that has none.
"""
import html
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "PRIVACY.md")
OUT = os.path.join(ROOT, "privacy.html")

EMAIL_RE = re.compile(r"\b[\w.+-]+@[\w-]+\.[\w.]+\b")


def inline(text):
    """Escape first, then the four spans the document actually uses."""
    text = html.escape(text)
    # Code spans are lifted out before anything else, so a `*` inside one is
    # a character and not an accident of emphasis.
    spans = []

    def stash(m):
        spans.append(m.group(1))
        return f"\x00{len(spans) - 1}\x00"

    text = re.sub(r"`([^`]+)`", stash, text)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
    text = re.sub(r"\[(.+?)\]\((.+?)\)", r'<a href="\2">\1</a>', text)
    text = EMAIL_RE.sub(lambda m: f'<a href="mailto:{m.group(0)}">{m.group(0)}</a>', text)
    return re.sub(r"\x00(\d+)\x00", lambda m: f"<code>{spans[int(m.group(1))]}</code>", text)


def cells(line):
    return [c.strip() for c in line.strip().strip("|").split("|")]


def render(md):
    out, i = [], 0
    lines = md.split("\n")
    while i < len(lines):
        line = lines[i]

        if not line.strip():
            i += 1
        elif line.startswith("#"):
            level = len(line) - len(line.lstrip("#"))
            out.append(f"<h{level}>{inline(line[level:].strip())}</h{level}>")
            i += 1
        elif line.startswith("|"):
            head = cells(line)
            i += 2   # the header row and its dashes
            body = []
            while i < len(lines) and lines[i].startswith("|"):
                body.append(cells(lines[i]))
                i += 1
            th = "".join(f"<th>{inline(c)}</th>" for c in head)
            rows = "".join(
                "<tr>" + "".join(f"<td>{inline(c)}</td>" for c in r) + "</tr>" for r in body
            )
            out.append(f"<table><thead><tr>{th}</tr></thead><tbody>{rows}</tbody></table>")
        elif line.startswith("- "):
            items = []
            while i < len(lines) and (lines[i].startswith("- ") or lines[i].startswith("  ")):
                if lines[i].startswith("- "):
                    items.append(lines[i][2:].strip())
                else:                      # a wrapped line belongs to the item above
                    items[-1] += " " + lines[i].strip()
                i += 1
            out.append("<ul>" + "".join(f"<li>{inline(x)}</li>" for x in items) + "</ul>")
        else:
            para = []
            while i < len(lines) and lines[i].strip() and not lines[i][0] in "#|-":
                para.append(lines[i].strip())
                i += 1
            out.append(f"<p>{inline(' '.join(para))}</p>")
    return "\n".join(out)


PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#14121c">
<meta name="description" content="What Little RPG stores, what it sends and what it never touches.">
<title>Little RPG, Privacy Policy</title>
<link rel="icon" href="assets/icons/icons.png" type="image/png">
<!-- GENERATED by tools/build_privacy.py from PRIVACY.md. Do not edit this
     file: edit the markdown and rebuild, or the two will disagree and the
     one a store reads is this one. -->
<style>
:root {{
  --bg: #120e0c; --panel: #1c1512; --line: #402e2b;
  --ink: #f2e6c8; --dim: #a89272; --gold: #ebb85b; --wood: #a15c34;
}}
* {{ box-sizing: border-box; margin: 0; padding: 0; }}
body {{
  background: var(--bg); color: var(--ink);
  font-family: ui-monospace, "SF Mono", "Cascadia Mono", Menlo, Consolas, monospace;
  font-size: 15px; line-height: 1.65;
  padding: 24px 18px 72px;
  -webkit-text-size-adjust: 100%;
}}
main {{ max-width: 46rem; margin: 0 auto; }}
h1 {{
  font-size: 1.5rem; color: var(--gold); line-height: 1.3;
  margin: 8px 0 4px;
}}
h2 {{
  font-size: 1.05rem; color: var(--gold); margin: 40px 0 10px;
  padding-bottom: 6px; border-bottom: 2px solid var(--line);
}}
p, ul, table {{ margin: 12px 0; }}
ul {{ padding-left: 1.1rem; }}
li {{ margin: 4px 0; }}
strong {{ color: #fff4d8; }}
em {{ color: var(--dim); font-style: normal; }}
code {{
  background: var(--panel); border: 1px solid var(--line);
  border-radius: 3px; padding: 1px 5px; font-size: 0.9em; color: var(--gold);
}}
a {{ color: var(--gold); }}
table {{ border-collapse: collapse; width: 100%; font-size: 0.92em; }}
th, td {{
  border: 1px solid var(--line); padding: 7px 10px;
  text-align: left; vertical-align: top;
}}
th {{ background: var(--panel); color: var(--gold); }}
.crumb {{
  display: inline-block; margin-bottom: 18px;
  color: var(--dim); text-decoration: none;
}}
.crumb:hover {{ color: var(--gold); }}
.foot {{
  margin-top: 48px; padding-top: 14px; border-top: 2px solid var(--line);
  color: var(--dim); font-size: 0.86em;
}}
</style>
</head>
<body>
<main>
<a class="crumb" href="./">&lt; Little RPG</a>
{body}
<p class="foot">This page is generated from PRIVACY.md in the game's public
source, so what you read here is what ships.</p>
</main>
</body>
</html>
"""


def main():
    with open(SRC, encoding="utf-8") as fh:
        md = fh.read()
    page = PAGE.format(body=render(md))
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(page)
    print(f"privacy.html  ({len(page) / 1024:.0f} KB from PRIVACY.md)")


if __name__ == "__main__":
    main()
